name: Ultimate-Gaming-VM-V41-MAX-FPS
on: workflow_dispatch

jobs:
  launch-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle & Run
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          M_USER: ${{ secrets.MEGA_EMAIL }}
          M_PASS: ${{ secrets.MEGA_PASSWORD }}
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          
          # This command pushes your script to Kaggle directly
          kaggle kernels push -p .
