name: Ultimate-Gaming-VM-V41-MAX-FPS
on: workflow_dispatch

jobs:
  launch-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Kaggle GPU Engine
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Ultimate-Gaming-VM-GPU"
          enable_gpu: "enable"
          # This tells it to look in the main folder
          code_file: "./gpu_runner.py"
